CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS agent_conversations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    fastagi_conversation_id text NOT NULL UNIQUE,
    agent_id text NOT NULL,
    app_user text NOT NULL,
    title text,
    status text NOT NULL DEFAULT 'active',
    client_session_id text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    last_message_at timestamptz
);

CREATE TABLE IF NOT EXISTS agent_messages (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id uuid NOT NULL REFERENCES agent_conversations(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('user', 'assistant', 'system', 'tool')),
    content text NOT NULL DEFAULT '',
    fastagi_message_id text,
    fastagi_parent_message_id text,
    request_query text,
    request_inputs jsonb NOT NULL DEFAULT '{}'::jsonb,
    request_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    response_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    attached_dataset_id text,
    status text NOT NULL DEFAULT 'completed',
    error_message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz
);

CREATE TABLE IF NOT EXISTS agent_message_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id uuid REFERENCES agent_messages(id) ON DELETE CASCADE,
    conversation_id uuid NOT NULL REFERENCES agent_conversations(id) ON DELETE CASCADE,
    sequence_no integer NOT NULL,
    event_type text NOT NULL,
    answer_delta text,
    raw_event jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (conversation_id, sequence_no)
);

CREATE INDEX IF NOT EXISTS idx_agent_conversations_app_user_updated
    ON agent_conversations (app_user, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_conversations_agent_updated
    ON agent_conversations (agent_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_messages_conversation_created
    ON agent_messages (conversation_id, created_at);

CREATE INDEX IF NOT EXISTS idx_agent_messages_fastagi_message_id
    ON agent_messages (fastagi_message_id)
    WHERE fastagi_message_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_agent_message_events_message_sequence
    ON agent_message_events (message_id, sequence_no)
    WHERE message_id IS NOT NULL;
